# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('symkalaweb', '0004_auto_20160125_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 26, 19, 32, 32, 818000, tzinfo=utc)),
        ),
    ]
