# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symkalaweb', '0007_auto_20160126_1444'),
        ('symkalaweb', '0006_auto_20160120_1814'),
    ]

    operations = [
    ]
