# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 16:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('symkalaweb', '0008_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='symkalaweb.File')),
                ('tweet', models.CharField(blank=True, max_length=500)),
                ('author', models.CharField(blank=True, max_length=100)),
            ],
            bases=('symkalaweb.file',),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 27, 16, 43, 32, 292000, tzinfo=utc)),
        ),
    ]
